[package]
name = "fafrost"
version = "0.1.0"
edition = "2024"

[dependencies]
bitcoin = "0.32"
rand = "0.8"
rand_core = { version = "0.6", features = ["getrandom"] }
sha2 = "0.10"
k256 = { version = "0.13", default-features = false, features = [
    "arithmetic",
    "hash2curve",
] }
curve25519-dalek = { version = "4", features = [
    "group",
    "rand_core",
    "digest",
] }
group = "0.13"
ff = "0.13"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
hex = "0.4"
bitcoin_hashes = "0.14"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

# RFC 8032 verifier.
ed25519-dalek = "2"

[[bench]]
name = "fafrost"
harness = false
